"""empty message

Revision ID: 41433d6fe4f4
Revises: 6a7b465542ec
Create Date: 2022-07-12 09:13:52.279602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41433d6fe4f4'
down_revision = '6a7b465542ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('access_token', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Users')
    # ### end Alembic commands ###
