"""empty message

Revision ID: ed7e83a35506
Revises: 44058644a021
Create Date: 2022-07-08 14:20:14.820948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed7e83a35506'
down_revision = '44058644a021'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Copies',
    sa.Column('copy_id', sa.String(), autoincrement=True, nullable=False),
    sa.Column('isbn', sa.String(), nullable=True),
    sa.Column('user_checked_out', sa.Integer(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('copy_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Copies')
    # ### end Alembic commands ###
